version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts
      
jobs:
  run-my-test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install
          npm test

workflows:
  my-custom-workflow:
    jobs:
      - run-my-test