version: 2.1
jobs:
  test:
    docker:
      - image: ianwalter/puppeteer:latest
    steps:
      - checkout
      - run:
          name: Make Report Directory
          command: mkdir report
      - run:
          name: Download Selenium Standalone Server
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium Standalone Server
          command: java -jar selenium-server-standalone-3.5.3.jar -log report/selenium.log
          background: true
      - run:
          name: Install Node Modules
          command: npm install
      - run:
          name: Test
          command: npm test
      - store_test_results:
          path: report
workflows:
  version: 2
  test:
    jobs:
      - test
