name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm install
        - name: UI Test
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm run test-ui
        - name: API Test
          uses: ianwalter/puppeteer-container@afefc4bee7341a77baa94503da684e2895ea5d30
          with:
            args: npm run test-api   
        - name: Publish Unit Test Results
          uses: EnricoMi/publish-unit-test-result-action/composite@v1
          if: always()
          with:
             files: junit-results/**/*.xml
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: allure-results
            path: allure-results
 
