name: Responsive Fight Test
on: [push, pull_request]
jobs:
  UI-test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Node
          uses: actions/setup-node@v2
          with:
           node-version: 12
        - name: Install Npm Dependencies
          run : npm install
        - name: UI Test
          run : npm run test-ui
        - name: Publish Unit Test Results
          uses: EnricoMi/publish-unit-test-result-action/composite@v1
          if: always()
          with:
             files: junit-results/**/*.xml
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: allure-results
            path: allure-results
          
  API-test:
          runs-on: ubuntu-latest
          steps:
           - name: Checkout
             uses: actions/checkout@v2
           - name: Install Node
             uses: actions/setup-node@v2
             with:
               node-version: 12
           - name: Install Npm Dependencies
             run : npm install
           - name: API Test
             run : npm run test-api 
           - name: Cucumber Report to Annotations
             if: ${{ always() }}
             uses: deblockt/cucumber-report-annotations-action@v1.7
             with:
               access-token: ${{ secrets.GITHUB_TOKEN }}
               path: "**/cucumber-report.json"
        
        
 
